
def jsonify()
  use_frameworks!
  pod 'Jsonify', :path => '../'
end

target 'JsonifyDemoiOS' do
  platform :ios, '9.0'
  jsonify()
end

target 'JsonifyDemoOSX' do
  platform :osx, '10.10'
  jsonify()
end
